config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, controllers: {omniauth_callbacks:
    "users/omniauth_callbacks",sessions: "users/sessions"}
  root "static_pages#home"
  get "/facebook/login", to: "facebooks#login", as: "login"
  get "/facebook/login/success", to: "facebooks#login_success", as: "success"

  resources :users
  resource :facebook
  resources :words, only: [:index]
  resources :courses, only: [:index]
  resources :searchs
  resources :relationships, only: [:create, :destroy]
  resources :lessons do
    resources :results, only: [:index]
  end
  resources :lessons
end

app/controllers/facebooks_controller.rb
class FacebooksController < ApplicationController
  before_action :get_user_details
  before_action :create_graph_api_object, only: [:show, :create]

  def login
    response_body = get_api_request "oauth/access_token?
    client_id=#{ENV["app_id"]}&client_secret=#{ENV["app_secret"]}&code=#{params[:code]}&redirect_uri=#{login_url}"
    access_token = response_body["access_token"]
    details = get_api_request "me?fields=email,name&access_token=#{access_token}"
    user = User.find_by email: details["email"]
    if !user
      user = User.create email: details["email"], name: details["name"], password: Devise.friendly_token, access_token: access_token
    else
      user.update_attributes access_token: access_token
    end
    sign_in user
    redirect_to new_facebook_path
  end

  def show
    @edge = @graph.get_connections params[:node], params[:edge], fields: params[:fields]
  end

  def new
  end

  def create
     responses = @graph.get_connections "me", "accounts"
     graph_page = Koala::Facebook::API.new responses[0]["access_token"]
    if params[:publish]
      responses = graph_page.put_connections "me","feed", message: params[:message]
      # responses = graph_page.put_object nil,"2779270585446576_2786495418057426", message: params[:message]
      # responses = graph_page.put_comment "2779270585446576_2786495418057426", params[:message]
      # responses = graph_page.put_like "2573340392737278_2590531271018190"
    elsif params[:edit]
      most_recent_post = graph_page.get_connections("me", "feed")[0]
      responses = graph_page.put_object nil, most_recent_post["id"], message: params[:message], fields: "id"
    elsif params[:batch]
      most_recent_post = graph_page.get_connections("me", "feed")[0]
      responses = graph_page.batch do |batch_api|
        params[:comment].split(";").each do |comment|
          batch_api.put_comment most_recent_post["id"], comment
        end
        batch_api.put_like most_recent_post["id"]
      end
      responses = responses[0]
    else
      responses = @graph.put_connections "me", "feed", message: params[:message]
    end
    redirect_to "https://www.facebook.com/#{responses["id"]}"
  end

  def edit
  end

  def update
    responses = @graph.get_connections "me", "accounts"
    graph_page = Koala::Facebook::API.new responses[0]["access_token"]
    most_recent_post = graph_page.get_connections("me", "feed")[0]
    responses = graph_page.put_object most_recent_post, message: params[:message]
    redirect_to "https://www.facebook.com/#{responses["id"]}"
  end

  private
    def create_graph_api_object
      @graph = Koala::Facebook::API.new current_user.access_token
    end

    def get_api_request endpoint
      uri = URI "https://graph.facebook.com/v3.2/#{endpoint}"
      response_body = JSON.parse Net::HTTP.get_response(uri).body
    end
end

app/views/facebooks/edit.html.erb
<div id="fb-root"></div>
<fb:login-button scope="user_birthday,user_hometown,user_location,user_likes,user_events,user_photos,user_videos,user_friends,user_status,user_tagged_places,user_posts,user_gender,user_link,user_age_range,email,read_insights,read_audience_network_insights,publish_video,manage_pages,pages_manage_cta,pages_manage_instant_articles,pages_show_list,publish_pages,read_page_mailboxes,ads_management,ads_read,business_management,pages_messaging,pages_messaging_phone_number,pages_messaging_subscriptions,instagram_basic,instagram_manage_comments,instagram_manage_insights,publish_to_groups,groups_access_member_info,leads_retrieval,public_profile">
</fb:login-button>

<div class="form-facebook">
<%= form_tag facebook_path, method: :post, multipart: true do %>
  <div class="form-group">
    <%= label_tag "node", "Node", class: "form-label" %>
    <%= text_field_tag "node", nil , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag "edge", "Edge", class: "form-label" %>
    <%= text_field_tag "edge", nil , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag "fields", "Fields", class: "form-label" %>
    <%= text_field_tag "fields", nil , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag "access_token", "Access token", class: "form-label" %>
    <%= text_field_tag "access_token" , nil, class: "form-control access_token"%>
  </div>
  <button type="submit" class="btn btn-danger btn-block">Get node</button>
<% end %>
</div>

app/views/facebooks/example.html.erb
<div id="fb-root"></div>
<fb:login-button scope="user_birthday,user_hometown,user_location,user_likes,user_events,user_photos,user_videos,user_friends,user_status,user_tagged_places,user_posts,user_gender,user_link,user_age_range,email,read_insights,read_audience_network_insights,publish_video,manage_pages,pages_manage_cta,pages_manage_instant_articles,pages_show_list,publish_pages,read_page_mailboxes,ads_management,ads_read,business_management,pages_messaging,pages_messaging_phone_number,pages_messaging_subscriptions,instagram_basic,instagram_manage_comments,instagram_manage_insights,publish_to_groups,groups_access_member_info,leads_retrieval,public_profile">
</fb:login-button>
<div class="form-facebook">
<%= form_tag "https://graph.facebook.com/me/feed", method: :post, multipart: true do %>
  <div class="form-group">
    <%= label_tag "message", "Message", class: "form-label" %>
    <%= text_field_tag "message", nil , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag "access_token", "Access token", class: "form-label" %>
    <%= text_field_tag "access_token" , nil, class: "form-control access_token"%>
    <button type="button" class="btn btn-success" onclick="insertAccessToken();">Generate</button>
  </div>
  <button type="submit" class="btn btn-danger btn-block">Send</button>
<% end %>
</div>

<div class="form-facebook">
  <h3> Show page_id </h3>
  <%= form_tag "https://graph.facebook.com/2779270585446576", method: :get, multipart: true do %>
  <div class="form-group">
    <%= label_tag "access_token", "Access token", class: "form-label" %>
    <%= text_field_tag "access_token" , nil, class: "form-control access_token"%>
  </div>
  <div class="form-group">
    <%= label_tag "fields", "Fields", class: "form-label" %>
    <%= text_field_tag "fields" , nil, class: "form-control"%>
  </div>
  <button type="submit" class="btn btn-danger btn-block">Send</button>
<% end %>
</div>

<div class="form-facebook">
  <h3> Show permissions </h3>
  <div class="form-group">
  <%= form_tag "https://graph.facebook.com/me/permissions", method: :get, multipart: true do %>
    <%= label_tag "access_token", "Access token", class: "form-label" %>
    <%= text_field_tag "access_token" , nil, class: "form-control access_token"%>
  </div>
  <button type="submit" class="btn btn-danger btn-block">Send</button>
<% end %>
</div>

<div class="form-facebook">
<h3>Cap quyen</h3>
  <%= label_tag "quyen", "Quyen", class: "form-label" %>
  <%= text_field_tag "quyen", nil, class: "form-control" %>
  <button type="button" class="btn btn-primary" onclick="RequestLoginFB();">Cap them quyen</button>
</div>


<!-- Cac quyen
user_birthday,
user_hometown,
user_location,
user_likes,
user_events,
user_photos,
user_videos,
user_friends,
user_status,
user_tagged_places,
user_posts,
user_gender,
user_link,
user_age_range,
email,
read_insights,
read_audience_network_insights,
publish_video,
manage_pages,
pages_manage_cta,
pages_manage_instant_articles,
pages_show_list,
publish_pages,
read_page_mailboxes,
ads_management,
ads_read,
business_management,
pages_messaging,
pages_messaging_phone_number,
pages_messaging_subscriptions,
instagram_basic,
instagram_manage_comments,
instagram_manage_insights,
publish_to_groups,
groups_access_member_info,
leads_retrieval,
public_profile -->

app/views/facebooks/login.html.erb
<div class="form-facebook login">
<%= form_tag "https://graph.facebook.com/v3.2/oauth/access_token", method: :get do %>
  <div class="form-group">
    <%= hidden_field_tag "client_id", ENV["app_id"] %>
    <%= hidden_field_tag "redirect_uri", login_url %>
    <%= hidden_field_tag "client_secret", ENV["app_secret"] %>
    <%= hidden_field_tag "code", @code %>
  </div>
  <button type="submit" class="btn btn-success btn-block">Save access token to your account</button>
<% end %>
</div>

app/views/facebooks/new.html.erb
<% unless user_signed_in? %>
<div class="form-facebook login">
<%= form_tag "https://www.facebook.com/v3.2/dialog/oauth", method: :get do %>
  <div class="form-group">
    <%= hidden_field_tag "client_id", ENV["app_id"] %>
    <%= hidden_field_tag "scope", Settings.facebook.permissions %>
    <%= hidden_field_tag "redirect_uri", login_url %>
  </div>
  <button type="submit" class="btn btn-primary btn-block">Login facebook</button>
<% end %>
</div>
<% else %>

<div class="form-facebook">
<%= form_tag facebook_path, method: :post, multipart: true do %>
  <div class="form-group">
    <%= label_tag "message", "Message", class: "form-label" %>
    <%= text_field_tag "message", nil , class: "form-control" %>
    <%= hidden_field_tag "publish", nil %>
    <%= hidden_field_tag "fields", "id" %>
  </div>
  <div class="form-group">
    <%= hidden_field_tag "access_token" , @current_user.access_token, class: "form-control"%>
  </div>
  <button type="submit" class="btn btn-danger btn-block">Publish to page</button>
<% end %>
</div>

<div class="form-facebook">
<%= form_tag facebook_path, method: :post, multipart: true do %>
  <div class="form-group">
    <%= label_tag "message", "Message", class: "form-label" %>
    <%= text_field_tag "message", nil , class: "form-control" %>
    <%= hidden_field_tag "edit", nil %>
    <%= hidden_field_tag "fields", "id" %>
  </div>
  <div class="form-group">
    <%= hidden_field_tag "access_token" , @current_user.access_token, class: "form-control"%>
  </div>
  <button type="submit" class="btn btn-danger btn-block">Edit most recent post</button>
<% end %>
</div>

<div class="form-facebook">
<%= form_tag facebook_path, method: :post, multipart: true do %>
  <div class="form-group">
    <%= label_tag "comment", "Multi comment", class: "form-label" %>
    <%= text_field_tag "comment", nil , class: "form-control" %>
    <%= hidden_field_tag "batch", nil %>
    <%= hidden_field_tag "fields", "id" %>
    <%= hidden_field_tag "access_token" , @current_user.access_token, class: "form-control"%>
  </div>
  <button type="submit" class="btn btn-danger btn-block">Add multi comments</button>
<% end %>
</div>

<div class="form-facebook">
<%= form_tag facebook_path, method: :get, multipart: true do %>
  <div class="form-group">
    <%= label_tag "node", "Node", class: "form-label" %>
    <%= text_field_tag "node", nil , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag "edge", "Edge", class: "form-label" %>
    <%= text_field_tag "edge", nil , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag "fields", "Fields", class: "form-label" %>
    <%= text_field_tag "fields", nil , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag "access_token", "Access token", class: "form-label" %>
    <%= hidden_field_tag "access_token" , @current_user.access_token, class: "form-control"%>
  </div>
  <button type="submit" class="btn btn-danger btn-block">Get node</button>
<% end %>
</div>
<% end %>

app/views/facebooks/show.html.erb
<div id="fb-root"></div>
<fb:login-button scope="user_birthday,user_hometown,user_location,user_likes,user_events,user_photos,user_videos,user_friends,user_status,user_tagged_places,user_posts,user_gender,user_link,user_age_range,email,read_insights,read_audience_network_insights,publish_video,manage_pages,pages_manage_cta,pages_manage_instant_articles,pages_show_list,publish_pages,read_page_mailboxes,ads_management,ads_read,business_management,pages_messaging,pages_messaging_phone_number,pages_messaging_subscriptions,instagram_basic,instagram_manage_comments,instagram_manage_insights,publish_to_groups,groups_access_member_info,leads_retrieval,public_profile">
</fb:login-button>
<h4>Show response node</h4>
<%= @node %>
<h4>Show response edge</h4>
<%= @edge %>