config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, controllers: {omniauth_callbacks:
    "users/omniauth_callbacks",sessions: "users/sessions"}
  root "static_pages#home"
  get "/facebook/login", to: "facebooks#login", as: "login"
  get "/facebook/login/success", to: "facebooks#login_success", as: "success"

  resources :users
  resource :facebook
  resources :words, only: [:index]
  resources :courses, only: [:index]
  resources :searchs
  resources :relationships, only: [:create, :destroy]
  resources :lessons do
    resources :results, only: [:index]
  end
  resources :lessons
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @courses = Course.all.sort_by{|course| Course.with_users[course.id] || 0}
      .reverse!.take Settings.courses.popular_course
    @course_with_users = Course.with_users
  end
end

app/views/static_pages/_counter.html.erb
<i class="fa fa-bell-o fa-3x"></i>
<li>
  <span id="notification-counter"><%= counter %></span>
</li>

app/views/static_pages/_header.html.erb
<header class="header">
  <!-- Header Content -->
  <div class="header_container">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="header_content d-flex flex-row
            align-items-center justify-content-start">
            <div class="logo_container">
              <a href=<%= root_path %>>
                <div class="logo_text"><%= t".ht" %>
                  <span><%= t".edu" %></span></div>
              </a>
            </div>
            <nav class="main_nav_contaner ml-auto">
              <ul class="main_nav">
                <div id="menu">
                <li class="link active">
                  <%= link_to t(".home"), root_path %>
                </li>

                <li class="link"><%= link_to t(".about"), "#" %></li>

                <% if user_signed_in? %>
                  <li class="link"><%= link_to t(".courses"), courses_path %></li>

                  <li class="link"><%= link_to t(".word_list"), words_path %></li>

                  <li class="link">
                    <%= link_to t(".logout"), destroy_user_session_path, method: :delete %>
                  </li>

                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <%= t ".user" %> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li class="dropdown-item"><%= link_to t(".profile"), @current_user %></li>
                      <li class="dropdown-item"><%= link_to t(".lessons"), lessons_path %></li>
                      <div class="dropdown-divider"></div>
                      <li class="dropdown-item">
                        <%= link_to t(".logout"), destroy_user_session_path, method: :delete %>
                      </li>
                    </ul>
                  </li>

                  <%= render "static_pages/notification_center" %>

                  <div class="search_button"><i class="fa fa-search"
                   aria-hidden="true"></i></div>

                <% else %>
                  <li class="link">
                    <%= link_to t(".login"), new_user_session_path %>
                  </li>
                <% end %>
              </div>
              </ul>
              <!-- Hamburger -->
            </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  <!-- Header Search Panel -->
  <div class="header_search_container">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="header_search_content d-flex flex-row align-items-center justify-content-end">
            <%= form_tag searchs_path, method: :get,
              class: "header_search_form" do %>
              <%= text_field_tag :query, params[:query],
                class: "search_input", placeholder: t(".search"),
                 required: true %>
              <%= button_tag fa_icon(t(".search_icon"), aria: {hidden: true}),
                class: "header_search_button d-flex flex-column align-items-center justify-content-center" %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

app/views/static_pages/_notification_center.html.erb
<ul class="notificator bell-btn">
  <a href="#" id="open_notification">
    <%= render "static_pages/counter" , counter: @current_user.number_of_activities %>
  </a>
  <div id="notificationContainer">
    <div id="notificationTitle"><%= t".notifications" %></div>
    <div id="notificationsBody" class="notifications">
      <ul id="notificationList">
        <%= render_activity @activities %>
      </ul>
    </div>
    <div id="notificationFooter"></div>
  </div>
</ul>

app/views/static_pages/home.html.erb
<% provide(:title, (t".home_title") )%>
<div class="super_container">
 <div class="courses">
    <div class="section_background parallax-window"
      data-parallax="scroll"
        data-image-src="images/courses_background.jpg" data-speed="0.8">
    </div>
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="section_title_container text-center">
            <h2 class="section_title"><%= t ".welcome" %></h2>
            <div class="section_subtitle">
              <p><%= t ".description" %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="row courses_row">
          <%= render @courses %>
        </div>
        <div class="col">
          <div class="courses_button trans_200">
            <%= link_to t(".all_courses"), courses_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>