config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, controllers: {omniauth_callbacks:
    "users/omniauth_callbacks",sessions: "users/sessions"}
  root "static_pages#home"
  get "/facebook/login", to: "facebooks#login", as: "login"
  get "/facebook/login/success", to: "facebooks#login_success", as: "success"

  resources :users
  resource :facebook
  resources :words, only: [:index]
  resources :courses, only: [:index]
  resources :searchs
  resources :relationships, only: [:create, :destroy]
  resources :lessons do
    resources :results, only: [:index]
  end
  resources :lessons
end

app/models/course.rb
class Course < ApplicationRecord
  include PublicActivity::Common
  mount_uploader :image, PictureUploader
  has_many :words
  has_many :lessons, dependent: :destroy
  scope :with_users, -> {Lesson.includes(:course).group(:course_id)
    .count(:user_id)}
  delegate :size, to: :words, prefix: true

  def search_data
    {
      name: name,
      description: description
    }
  end
end

app/views/public_activity/course/_counter.html.erb
<i class="fa fa-bell-o fa-3x"></i>
<li>
  <span id="notification-counter"><%= counter %></span>
</li>

app/views/public_activity/course/_finished.html.erb
<li>
  <div class="comment_item d-flex flex-row align-items-start jutify-content-start">
    <div class="comment_image"><div><%= link_to image_tag(activity.owner.image.url), courses_path %></div></div>
    <div class="comment_content">
      <div class="comment_title_container d-flex flex-row align-items-center justify-content-start">
        <div class="comment_author"><%= link_to t(".course"), courses_path %></div>
        <div class="comment_time ml-auto"><%= time_ago_in_words(activity.created_at) %></div>
      </div>
      <div class="comment_text">
      <p>
        <span><%= link_to(activity.owner.name, user_path(activity.recipient)) <<
          t(".finish") %></span>
        <span><%= link_to Course.find(activity.trackable_id)
          .name, courses_path %></span>
      </p>
      </div>
    </div>
  </div>
</li>